---
title: "Data Science Tools"
---

## Materials for Lessons on Git and GitHub

Slides are at: [https://stats-tgeorge.github.io/G_GH_Workshop_2024/Intro_Git_Github.html](https://stats-tgeorge.github.io/G_GH_Workshop_2024/Intro_Git_Github.html#/title-slide). Short link at <https://bit.ly/DSToolsGH>.


## Workshop Round 1

- Introduction into Git commands and terminology
- Create GitHub accounts and general overview
- Practice forking a repo, creating a new file, and pull-request
- Merge of pull request
- How to revert a repo change
- Creating website with GitHub Pages 
- Teaching GitHub
- Using GitHub to Teach

## Workshop Round 2 (50%-70% overlap)

- Introduction into Git commands and terminology
- Create GitHub accounts and general overview
- Practice forking a repo, creating a new file, and pull-request
 *OR*
- Go to GitHub page of opening talk, fork the repo, fix the mistakes, then pull-request
- Merge of pull request
  * Show GitHub desktop, RStudio, and Quarto all working together
- Teaching GitHub
- Using GitHub to Teach


### Resources

Teaching with GitHub and R, **ghclass** R package. <https://github.com/rundel/ghclass>

<https://docs.github.com/en/get-started/start-your-journey/git-and-github-learning-resources>

<https://github.com/skills/introduction-to-github?tab=readme-ov-file>

GitHub Educators <https://docs.github.com/en/education/quickstart>

<https://hbctraining.github.io/Training-modules/Git-Github>

<https://swcarpentry.github.io/git-novice/>

<https://joeyklee.github.io/friendly-github-intro/#schedule>

Happy Git and GitHub for the useR <https://happygitwithr.com/>

### References

-   Dogucu, M., & Çetinkaya-Rundel, M. (2022). Tools and Recommendations for Reproducible Teaching. Journal of Statistics and Data Science Education, 0(ja), 1–25. https://doi.org/10.1080/26939169.2022.2138645

-   Beckman, M. D., Çetinkaya-Rundel, M., Horton, N. J., Rundel, C. W., Sullivan, A. J., & Tackett, M. (2021). Implementing Version Control With Git and GitHub as a Learning Objective in Statistics and Data Science Courses. Journal of Statistics and Data Science Education, 29(sup1), S132–S144. https://doi.org/10.1080/10691898.2020.1848485

-   Çetinkaya-Rundel, M., & Rundel, C. (2018). Infrastructure and Tools for Teaching Computing Throughout the Statistical Curriculum. The American Statistician, 72(1), 58–65. https://doi.org/10.1080/00031305.2017.1397549